/**
 * Resolves PoE gem and item icon URLs from the static poe-icons.json
 * generated by scripts/fetch-poe-icons.mjs.
 */

import type { PobGem, PobItem } from "@/domain/models";
import iconData from "@/data/poe-icons.json";

const gems = iconData.gems as Record<string, string>;
const uniques = iconData.uniques as Record<string, string>;
const baseTypes = iconData.baseTypes as Record<string, string>;

export function resolveGemIcon(gemName: string): string | undefined {
  if (!gemName) return undefined;

  // Exact match
  if (gems[gemName]) return gems[gemName];

  // Strip parenthetical: "Absolution (Absolution)" → "Absolution"
  const withoutParen = gemName.replace(/\s*\(.*\)\s*$/, "");
  if (withoutParen !== gemName && gems[withoutParen]) return gems[withoutParen];

  const base = withoutParen || gemName;

  // Try adding "Support" suffix (formatIdentifier strips it, but icons use full names)
  if (!base.includes("Support")) {
    const withSupport = `${base} Support`;
    if (gems[withSupport]) return gems[withSupport];
  }

  // Strip "Vaal " prefix
  const withoutVaal = base.replace(/^Vaal\s+/i, "");
  if (withoutVaal !== base) {
    if (gems[withoutVaal]) return gems[withoutVaal];
    // Also try "Vaal X" → "X Support"
    if (!withoutVaal.includes("Support") && gems[`${withoutVaal} Support`]) {
      return gems[`${withoutVaal} Support`];
    }
  }

  // Strip "Summon " prefix: "Summon Sentinel of Radiance" → "Sentinel of Radiance"
  const withoutSummon = base.replace(/^Summon\s+/i, "");
  if (withoutSummon !== base && gems[withoutSummon]) return gems[withoutSummon];

  // Normalize "of" casing: "Absolution of Inspiring" vs "Absolution Of Inspiring"
  const normalized = base.replace(/\bof\b/gi, "of");
  if (normalized !== base && gems[normalized]) return gems[normalized];

  // Case-insensitive fallback (rare but handles edge cases)
  const lowerName = base.toLowerCase();
  const match = Object.keys(gems).find((k) => k.toLowerCase() === lowerName);
  if (match) return gems[match];

  // Case-insensitive with "Support" suffix
  const lowerWithSupport = `${lowerName} support`;
  const matchSupport = Object.keys(gems).find((k) => k.toLowerCase() === lowerWithSupport);
  if (matchSupport) return gems[matchSupport];

  return undefined;
}

export function resolveItemIcon(
  item: Pick<PobItem, "title" | "baseType" | "rarity">,
): string | undefined {
  // Uniques: match by title
  if (item.rarity?.toLowerCase() === "unique" && uniques[item.title]) {
    return uniques[item.title];
  }

  // Match by base type
  if (item.baseType && baseTypes[item.baseType]) {
    return baseTypes[item.baseType];
  }

  // Fallback: title as base type (normal/magic items)
  if (baseTypes[item.title]) return baseTypes[item.title];

  return undefined;
}

/** Bulk-resolve icon URLs for gems (mutates in-place). */
export function resolveGemIcons(gemList: PobGem[]): void {
  for (const gem of gemList) {
    gem.iconUrl = resolveGemIcon(gem.name) ?? resolveGemIcon(gem.rawName);
    // rawName may be a PascalCase skillId like "SummonSentinelOfRadiance"
    // try splitting it into words as a last resort
    if (!gem.iconUrl && gem.rawName && !/\s/.test(gem.rawName)) {
      const spaced = gem.rawName
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .replace(/\bOf\b/g, "of")
        .replace(/\bAnd\b/g, "and");
      gem.iconUrl = resolveGemIcon(spaced);
    }
  }
}

/** Bulk-resolve icon URLs for items (mutates in-place). */
export function resolveItemIcons(items: PobItem[]): void {
  for (const item of items) {
    item.iconUrl = resolveItemIcon(item);
  }
}
